# Generated by Django 4.1.7 on 2023-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiTabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.TextField()),
                ('campo3', models.IntegerField()),
                ('campo4', models.DateField()),
                ('campo5', models.BooleanField()),
                ('campo6', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
