# Generated by Django 4.1.7 on 2023-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitabla',
            old_name='campo1',
            new_name='Clase',
        ),
        migrations.RenameField(
            model_name='mitabla',
            old_name='campo4',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='mitabla',
            old_name='campo6',
            new_name='Edad',
        ),
        migrations.RemoveField(
            model_name='mitabla',
            name='campo2',
        ),
        migrations.RemoveField(
            model_name='mitabla',
            name='campo3',
        ),
        migrations.RemoveField(
            model_name='mitabla',
            name='campo5',
        ),
        migrations.AddField(
            model_name='mitabla',
            name='Poblacion',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitabla',
            name='apellidos',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitabla',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
